@startuml
'https://plantuml.com/class-diagram

hide empty members

GaloApp *-- GaloMenu
GaloApp *-- BoardView
GaloApp *-- StatusBar
BoardView *-- "*" CellView
StatusBar *-- PlayerView
PlayerView *- CellView

@enduml