@startuml
'https://plantuml.com/state-diagram

[*] -> ByPoints

ByPoints --> ByPoints : next
ByPoints --> Forty : next
Forty --> Forty : next
Forty --> Deuce : next
Forty --> Game : next
Deuce -> Advantage : next
Advantage -> Game : next
Advantage -> Deuce : next

Game --> [*]

ByPoints : pointsA
ByPoints : pointsB
Advantage : player
Game : winner
Forty : player
Forty : pointsOther

@enduml