@startuml

skinparam backgroundcolor transparent

package tds as "pt.isel.tds" {
    package storage {
        [Storage]
        [TextFileStorage]
        [MemoryStorage]
        [MongoStorage]
        [MongoUtils]
    }
    package ttt {
        package model  {
            [Game]
            [Board]
            [Position]
            [BoardSerializer]
        }
        package ui {
            [Command]
            [Input]
            [Output]
        }
        [Main]
    }
}

Game .> Board
Board ..> Position

Main ..> Command
Main ..> Input
Main ..> Output
Main ..> Game
Command .> Game
Output ..> Game
Output ..> Board

TextFileStorage .> Storage
BoardSerializer ..> Storage
BoardSerializer .> Board

Main ..> BoardSerializer
'Main ..> TextFileStorage
Main ..> MongoStorage
Command ..> Storage
Game ..> Storage

MemoryStorage ..> Storage
MongoStorage ..> Storage
MongoStorage ..> MongoUtils
@enduml